//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGCONG
    {
        public int MABANGCONG { get; set; }
        public Nullable<System.DateTime> NGAYGIOVAO { get; set; }
        public Nullable<System.DateTime> NGAYGIORA { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
        public Nullable<int> MALOAICONG { get; set; }
    
        public virtual TB_LOAICONG TB_LOAICONG { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
