//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PHUCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PHUCAP()
        {
            this.TB_NHANVIENPHUCAP = new HashSet<TB_NHANVIENPHUCAP>();
        }
    
        public int MAPHUCAP { get; set; }
        public string TENPHUCAP { get; set; }
        public Nullable<double> SOTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIENPHUCAP> TB_NHANVIENPHUCAP { get; set; }
    }
}
